plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

require:
  - standard

inherit_gem:
  standard:
    - config/base.yml
    - config/ruby-3.3.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
