require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - standard

inherit_gem:
  standard:
    - config/base.yml
    - config/ruby-2.5.yml
    - config/ruby-2.7.yml
    - config/ruby-3.0.yml

AllCops:
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
