plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

require:
  - standard

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
